### ISSUE TITLE
Parsing error at a floating point number having fractional part starts with zero

### ISSUE THREAD

**Issue by aratama** [folkertdev/svg-path-lowlevel#1]
Hello,

I'm using this nice library in my personal project. Thanks a lot!

I found an issue when parsing a floating point number: For example, `"29.00783068240771"` is interpreted as  `29.783068240771`. It lacks leading zeros of the fractional part of the number. 

I believe there is a bug in [`fractionalConstant`](https://github.com/folkertdev/svg-path-lowlevel/blob/3.0.0/src/Path/LowLevel/ParserHelpers.elm#L127). It uses `digitSequence` to parse fractional part and it interprets the part as `Int`. It should hold the value as just a `String` instead of `Int` then join with the integer part.

**Comment by folkertdev** [comment]
Th is now published as version [4.0.0](https://package.elm-lang.org/packages/folkertdev/svg-path-lowlevel/4.0.0/)
